// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Sprint1_C_.Infrastructure.Data;

#nullable disable

namespace Sprint1_C_.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.Filial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Filiais");
                });

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.LeitorRfid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IpDispositivo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("PatioId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("PatioId");

                    b.ToTable("LeitoresRfid");
                });

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.LeituraRfid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("LeitorId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("TagId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("LeitorId");

                    b.HasIndex("TagId");

                    b.ToTable("LeiturasRfid");
                });

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.Moto", b =>
                {
                    b.Property<string>("Placa")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Modelo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("PatioId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("TagId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Placa");

                    b.HasIndex("PatioId");

                    b.ToTable("Motos");
                });

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.Patio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comprimento")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("FilialId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Largura")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("FilialId");

                    b.ToTable("Patios");
                });

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.TagRfid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("CodigoIdentificacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MotoPlaca")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("Id");

                    b.HasIndex("MotoPlaca")
                        .IsUnique();

                    b.ToTable("TagsRfid");
                });

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.LeitorRfid", b =>
                {
                    b.HasOne("Sprint1_C_.Domain.Entities.Patio", "Patio")
                        .WithMany("Leitores")
                        .HasForeignKey("PatioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patio");
                });

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.LeituraRfid", b =>
                {
                    b.HasOne("Sprint1_C_.Domain.Entities.LeitorRfid", "Leitor")
                        .WithMany("Leituras")
                        .HasForeignKey("LeitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sprint1_C_.Domain.Entities.TagRfid", "Tag")
                        .WithMany("Leituras")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Leitor");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.Moto", b =>
                {
                    b.HasOne("Sprint1_C_.Domain.Entities.Patio", "Patio")
                        .WithMany("Motos")
                        .HasForeignKey("PatioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patio");
                });

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.Patio", b =>
                {
                    b.HasOne("Sprint1_C_.Domain.Entities.Filial", "Filial")
                        .WithMany("Patios")
                        .HasForeignKey("FilialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filial");
                });

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.TagRfid", b =>
                {
                    b.HasOne("Sprint1_C_.Domain.Entities.Moto", "Moto")
                        .WithOne("Tag")
                        .HasForeignKey("Sprint1_C_.Domain.Entities.TagRfid", "MotoPlaca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Moto");
                });

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.Filial", b =>
                {
                    b.Navigation("Patios");
                });

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.LeitorRfid", b =>
                {
                    b.Navigation("Leituras");
                });

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.Moto", b =>
                {
                    b.Navigation("Tag")
                        .IsRequired();
                });

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.Patio", b =>
                {
                    b.Navigation("Leitores");

                    b.Navigation("Motos");
                });

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.TagRfid", b =>
                {
                    b.Navigation("Leituras");
                });
#pragma warning restore 612, 618
        }
    }
}
