// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sprint1_C_.Infrastructure.Data;

#nullable disable

namespace MottuFind_C_.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251107024329_AjusteModeloAtual")]
    partial class AjusteModeloAtual
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.Filial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TB_FILIAIS", (string)null);
                });

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.LeitorRfid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IpDispositivo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PatioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatioId");

                    b.ToTable("TB_LEITORES_RFID", (string)null);
                });

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.LeituraRfid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("LeitorId")
                        .HasColumnType("int");

                    b.Property<int>("TagRfidId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeitorId");

                    b.HasIndex("TagRfidId");

                    b.ToTable("TB_LEITURAS_RFID", (string)null);
                });

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.Moto", b =>
                {
                    b.Property<string>("Placa")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Placa");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PatioId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Placa");

                    b.HasIndex("PatioId");

                    b.ToTable("TB_MOTOS", (string)null);
                });

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.Patio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FilialId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("FilialId");

                    b.ToTable("TB_PATIOS", (string)null);
                });

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.TagRfid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoIdentificacao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MotoPlaca")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("MotoPlaca")
                        .IsUnique();

                    b.ToTable("TB_TAGS_RFID", (string)null);
                });

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Setor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TB_USUARIOS", (string)null);
                });

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.LeitorRfid", b =>
                {
                    b.HasOne("Sprint1_C_.Domain.Entities.Patio", "Patio")
                        .WithMany("Leitores")
                        .HasForeignKey("PatioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LEITORES_PATIOS");

                    b.Navigation("Patio");
                });

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.LeituraRfid", b =>
                {
                    b.HasOne("Sprint1_C_.Domain.Entities.LeitorRfid", "Leitor")
                        .WithMany("Leituras")
                        .HasForeignKey("LeitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LEITURAS_LEITORES");

                    b.HasOne("Sprint1_C_.Domain.Entities.TagRfid", "TagRfid")
                        .WithMany()
                        .HasForeignKey("TagRfidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LEITURAS_TAGS");

                    b.Navigation("Leitor");

                    b.Navigation("TagRfid");
                });

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.Moto", b =>
                {
                    b.HasOne("Sprint1_C_.Domain.Entities.Patio", "Patio")
                        .WithMany("Motos")
                        .HasForeignKey("PatioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MOTOS_PATIOS");

                    b.Navigation("Patio");
                });

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.Patio", b =>
                {
                    b.HasOne("Sprint1_C_.Domain.Entities.Filial", "Filial")
                        .WithMany("Patios")
                        .HasForeignKey("FilialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PATIOS_FILIAIS");

                    b.Navigation("Filial");
                });

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.TagRfid", b =>
                {
                    b.HasOne("Sprint1_C_.Domain.Entities.Moto", "Moto")
                        .WithOne("TagRfid")
                        .HasForeignKey("Sprint1_C_.Domain.Entities.TagRfid", "MotoPlaca")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_TAGS_MOTOS");

                    b.Navigation("Moto");
                });

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.Filial", b =>
                {
                    b.Navigation("Patios");
                });

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.LeitorRfid", b =>
                {
                    b.Navigation("Leituras");
                });

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.Moto", b =>
                {
                    b.Navigation("TagRfid")
                        .IsRequired();
                });

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.Patio", b =>
                {
                    b.Navigation("Leitores");

                    b.Navigation("Motos");
                });
#pragma warning restore 612, 618
        }
    }
}
