// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sprint1_C_.Infrastructure.Data;

#nullable disable

namespace MottuFind_C_.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.Filial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TB_FILIAIS", (string)null);
                });

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.LeitorRfid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IpDispositivo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PatioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatioId");

                    b.ToTable("TB_LEITORES_RFID", (string)null);
                });

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.LeituraRfid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LeitorId")
                        .HasColumnType("int");

                    b.Property<int>("TagRfidId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeitorId");

                    b.HasIndex("TagRfidId");

                    b.ToTable("TB_LEITURAS_RFID", (string)null);
                });

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.Moto", b =>
                {
                    b.Property<string>("Placa")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Placa");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Marca");

                    b.Property<int>("Modelo")
                        .HasColumnType("int")
                        .HasColumnName("Modelo");

                    b.Property<int>("PatioId")
                        .HasColumnType("int")
                        .HasColumnName("PatioId");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.HasKey("Placa");

                    b.HasIndex("PatioId");

                    b.ToTable("TB_MOTOS", (string)null);
                });

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.Patio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FilialId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FilialId");

                    b.ToTable("TB_PATIOS", (string)null);
                });

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.TagRfid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoIdentificacao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CodigoIdentificacao");

                    b.Property<string>("MotoPlaca")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("MotoPlaca");

                    b.HasKey("Id");

                    b.HasIndex("MotoPlaca")
                        .IsUnique();

                    b.ToTable("TB_TAGS_RFID", (string)null);
                });

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Setor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TB_USUARIO", (string)null);
                });

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.LeitorRfid", b =>
                {
                    b.HasOne("Sprint1_C_.Domain.Entities.Patio", "Patio")
                        .WithMany("Leitores")
                        .HasForeignKey("PatioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patio");
                });

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.LeituraRfid", b =>
                {
                    b.HasOne("Sprint1_C_.Domain.Entities.LeitorRfid", "Leitor")
                        .WithMany("Leituras")
                        .HasForeignKey("LeitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sprint1_C_.Domain.Entities.TagRfid", "TagRfid")
                        .WithMany()
                        .HasForeignKey("TagRfidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Leitor");

                    b.Navigation("TagRfid");
                });

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.Moto", b =>
                {
                    b.HasOne("Sprint1_C_.Domain.Entities.Patio", "Patio")
                        .WithMany("Motos")
                        .HasForeignKey("PatioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patio");
                });

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.Patio", b =>
                {
                    b.HasOne("Sprint1_C_.Domain.Entities.Filial", "Filial")
                        .WithMany("Patios")
                        .HasForeignKey("FilialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filial");
                });

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.TagRfid", b =>
                {
                    b.HasOne("Sprint1_C_.Domain.Entities.Moto", "Moto")
                        .WithOne("TagRfid")
                        .HasForeignKey("Sprint1_C_.Domain.Entities.TagRfid", "MotoPlaca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Moto");
                });

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.Filial", b =>
                {
                    b.Navigation("Patios");
                });

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.LeitorRfid", b =>
                {
                    b.Navigation("Leituras");
                });

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.Moto", b =>
                {
                    b.Navigation("TagRfid")
                        .IsRequired();
                });

            modelBuilder.Entity("Sprint1_C_.Domain.Entities.Patio", b =>
                {
                    b.Navigation("Leitores");

                    b.Navigation("Motos");
                });
#pragma warning restore 612, 618
        }
    }
}
